### PR TITLE
Serenity guide.zh cn

### PR DESCRIPTION
**Pull request by WuShenghui**
Hi @volkanceylan , I have translated serenity-guide into Chinese  that might useful for Chinese developers to use Serenity. Thanks for your great job.

### CODE REVIEW

**Comment by volkanceylan** [comment]
Omg, thats fantastic work, thank you very much. 

If i merge this request, english guide will be overridden so i'ii create another book in gitbook and share its link.

**Comment by WuShenghui** [comment]
Ok, that would be great.

**Comment by volkanceylan** [comment]
I added you as collabrator to both github and gitbook for Chinese guide. You should receive an invitation. You can use gitbook for easier updates.

**Comment by volkanceylan** [comment]
Merged manually, thanks.

**Pull request closed without merging**
